"""
Version 4, AI feature 4 — conversational AI chat panel.

Scope (see docs/plan): single-turn-per-message (build_context() is
rebuilt fresh per message, not held as server-side "memory"), no
streaming. Read-only relationship to features 2-3 — this module never
triggers a new digest or alert commentary; it only reads what already
exists.

Tool-calling was originally excluded entirely, deliberately deferred
as "a separate future decision" (see docs/Version_4/v4_plan.md). Later
resolved to a single, narrow tool: the AI can request a real
analyze_symbol() run (the same function AIAnalysisPanel's "Re-run"
button calls) when the trader explicitly asks for a fresh/official
analysis, via ChatReplyResponse.wants_reanalysis. No open-ended
function-calling loop — one fixed action, decided in the same
completion call that would otherwise produce a normal reply, executed
synchronously before the turn's assistant message is persisted.

Follows analyze_symbol's "never raise for an expected failure mode"
contract: AI off, InsufficientDataError, or a malformed reply all
degrade to a stored assistant message explaining that (grounded=False)
rather than an HTTP error or a crashed request. The reanalysis tool
call inherits the same contract — it never raises either.
"""
from __future__ import annotations

import logging

from backend.ai.analyze import analyze_symbol
from backend.ai.context import InsufficientDataError, build_context
from backend.ai.manager import ai_manager
from backend.ai.prompt import (
    CHAT_SYSTEM_PROMPT,
    UncertaintyResponse,
    build_chat_prompt,
    parse_chat_reply,
)
from backend.models import AlertTrigger, ChatMessage
from backend.repositories.chat_repository import ChatRepository

logger = logging.getLogger(__name__)

# How many prior turns (user + assistant messages combined) to include
# as transcript text in the prompt.
_TRANSCRIPT_TURNS = 6


def _build_alert_context(db, alert_trigger_id: int | None) -> dict | None:
    """Load the alert/trigger this chat was opened from, if any.

    Read-only — never re-triggers alert commentary generation, just
    reads what's already on the row (message/observed_value/
    ai_commentary if it's been generated by then).
    """
    if alert_trigger_id is None:
        return None
    trigger = db.query(AlertTrigger).filter(AlertTrigger.id == alert_trigger_id).first()
    if trigger is None:
        return None
    return {
        "symbol": trigger.symbol,
        "message": trigger.message,
        "observed_value": trigger.observed_value,
        "ai_commentary": trigger.ai_commentary,
        "triggered_at": str(trigger.triggered_at) if trigger.triggered_at else None,
    }


def answer_chat_message(session_id: int, user_content: str) -> tuple[ChatMessage, bool]:
    """Persist ``user_content`` as a user message, generate a reply,
    persist the assistant ChatMessage, and return ``(message,
    grounded)``.

    ``grounded`` isn't a persisted column (the stored transcript only
    has role/content, kept simple) — it's a per-turn hint for the
    immediate caller (the router's response), not part of chat
    history a later turn would need to see again.

    Never raises for an expected failure mode — AI-off, a
    context-building failure, or a malformed AI reply all produce a
    stored assistant message (grounded=False) explaining that, not an
    exception. An unexpected failure (e.g. the session doesn't exist)
    still raises — that's a caller bug, not a "the AI couldn't answer"
    case.
    """
    repo = ChatRepository()
    try:
        session = repo.get_session(session_id)
        if session is None:
            raise ValueError(f"chat session {session_id} not found")

        repo.add_message(session_id, "user", user_content)

        history = repo.get_messages(session_id, limit=_TRANSCRIPT_TURNS + 1)
        # Exclude the message we just added — it's passed separately
        # as `new_message`, not duplicated into the transcript.
        transcript = [(m.role, m.content) for m in history[:-1]][-_TRANSCRIPT_TURNS:]

        alert_context = _build_alert_context(repo.db, session.alert_trigger_id)

        reply_text: str
        grounded: bool
        try:
            context = build_context(session.symbol)
            context_dict = context.to_dict()
        except InsufficientDataError as e:
            logger.info("answer_chat_message: insufficient data for %s: %s", session.symbol, e)
            reply_text = (
                f"I don't have enough data on {session.symbol} yet to answer that."
            )
            grounded = False
        else:
            reply_text, grounded = _generate_reply(
                session.symbol, context_dict, transcript, user_content, alert_context,
            )

        assistant_message = repo.add_message(session_id, "assistant", reply_text)
        return assistant_message, grounded
    finally:
        repo.close()


def _generate_reply(
    symbol: str,
    context_dict: dict,
    transcript: list[tuple[str, str]],
    user_content: str,
    alert_context: dict | None,
) -> tuple[str, bool]:
    """Call the AI and parse its reply. Never raises — degrades to a
    plain "couldn't process" reply with grounded=False.

    When the AI's reply asks for ``wants_reanalysis``, runs the chat's
    one tool (see module docstring) instead of returning that reply
    verbatim.
    """
    if not ai_manager.is_available():
        return "AI is currently unavailable, so I can't answer that right now.", False

    try:
        resp = ai_manager.complete(
            prompt=build_chat_prompt(context_dict, transcript, user_content, alert_context),
            system=CHAT_SYSTEM_PROMPT,
            max_tokens=300,
        )
    except Exception as e:  # noqa: BLE001
        logger.warning("Chat AI call raised: %s", e)
        return "Something went wrong reaching the AI provider — please try again.", False

    if resp.text is None:
        return "AI is currently unavailable, so I can't answer that right now.", False

    try:
        parsed = parse_chat_reply(resp.text)
    except Exception as e:  # noqa: BLE001
        logger.info("Chat reply failed to parse: %s", e)
        return "I couldn't process that — could you rephrase?", False

    if parsed.wants_reanalysis:
        return _run_reanalysis(symbol)

    return parsed.reply, parsed.grounded


def _run_reanalysis(symbol: str) -> tuple[str, bool]:
    """Execute the chat's one tool call: a real analyze_symbol() run.

    Reuses analyze_symbol() itself — the same function
    AIAnalysisPanel's "Re-run" button calls — so a chat-triggered
    reanalysis carries the exact same safety contract (never raises;
    degrades to an UncertaintyResponse on AI-off/no-data/malformed
    reply). That degrade path is rendered here as a normal,
    grounded=False chat reply rather than surfaced as an error.
    """
    try:
        result = analyze_symbol(symbol)
    except Exception as e:  # noqa: BLE001 — the tool call must never crash the turn
        logger.warning("Chat-triggered reanalysis failed for %s: %s", symbol, e)
        return (
            "I tried to re-run the analysis but hit an error — please try again.",
            False,
        )

    if isinstance(result, UncertaintyResponse):
        return f"I tried to re-run the analysis for {symbol}, but {result.summary}", False

    return (
        f"I re-ran the analysis for {symbol}: trend is now {result.trend} "
        f"({result.confidence:.0%} confidence). {result.summary}",
        True,
    )
