"""
Version 4, AI feature 4 — conversational AI chat panel.

Scope (see docs/plan): single-turn-per-message (build_context() is
rebuilt fresh per message, not held as server-side "memory"), no
streaming. Read-only relationship to features 2-3 — this module never
triggers a new digest or alert commentary; it only reads what already
exists.

Tool-calling was originally excluded entirely, deliberately deferred
as "a separate future decision" (see docs/Version_4/v4_plan.md). Later
resolved to a single, narrow tool: the AI can request a real
analyze_symbol() run (the same function AIAnalysisPanel's "Re-run"
button calls) when the trader explicitly asks for a fresh/official
analysis, via ChatReplyResponse.wants_reanalysis. No open-ended
function-calling loop — one fixed action, decided in the same
completion call that would otherwise produce a normal reply, executed
synchronously before the turn's assistant message is persisted.

Follows analyze_symbol's "never raise for an expected failure mode"
contract: AI off, InsufficientDataError, or a malformed reply all
degrade to a stored assistant message explaining that (grounded=False)
rather than an HTTP error or a crashed request. The reanalysis tool
call inherits the same contract — it never raises either.
"""
from __future__ import annotations

import logging
from concurrent.futures import ThreadPoolExecutor

from backend.ai.analyze import analyze_symbol
from backend.ai.chat_symbols import resolve_turn_symbols
from backend.ai.context import InsufficientDataError, build_context
from backend.ai.manager import ai_manager
from backend.ai.market_baseline import build_market_baseline
from backend.ai.prompt import (
    CHAT_SYSTEM_PROMPT,
    UncertaintyResponse,
    build_chat_prompt,
    parse_chat_reply,
)
from backend.models import AlertTrigger, ChatMessage
from backend.models.chat import UNIVERSAL_SYMBOL
from backend.repositories.chat_repository import ChatRepository

logger = logging.getLogger(__name__)

# How many prior turns (user + assistant messages combined) to include
# as transcript text in the prompt.
_TRANSCRIPT_TURNS = 6


def _build_alert_context(db, alert_trigger_id: int | None) -> dict | None:
    """Load the alert/trigger this chat was opened from, if any.

    Read-only — never re-triggers alert commentary generation, just
    reads what's already on the row (message/observed_value/
    ai_commentary if it's been generated by then).
    """
    if alert_trigger_id is None:
        return None
    trigger = db.query(AlertTrigger).filter(AlertTrigger.id == alert_trigger_id).first()
    if trigger is None:
        return None
    return {
        "symbol": trigger.symbol,
        "message": trigger.message,
        "observed_value": trigger.observed_value,
        "ai_commentary": trigger.ai_commentary,
        "triggered_at": str(trigger.triggered_at) if trigger.triggered_at else None,
    }


def answer_chat_message(
    session_id: int, user_content: str
) -> tuple[ChatMessage, bool, list[str], list[str], list[str]]:
    """Persist ``user_content``, generate a reply, persist the assistant
    ChatMessage, and return
    ``(message, grounded, focus, partial, unavailable)``.

    Universal chat (2026-09-10): the turn resolves its own tickers from
    the message text (0..N, capped), always attaches a cheap
    market-wide baseline, and builds per-ticker quant context for each
    resolved symbol. ``focus`` is the tickers that got a full
    (warm-engine) context block; ``partial`` the ones with only live
    price / indicators (not in a watchlist); ``unavailable`` the ones
    that were named but had no data at all.

    ``grounded`` / ``focus`` / ``unavailable`` aren't persisted columns
    — they're per-turn hints for the router's response.

    Never raises for an expected failure mode — AI-off, a per-symbol
    context failure, or a malformed AI reply all produce a stored
    assistant message explaining that, not an exception. An unexpected
    failure (e.g. the session doesn't exist) still raises.
    """
    repo = ChatRepository()
    try:
        session = repo.get_session(session_id)
        if session is None:
            raise ValueError(f"chat session {session_id} not found")

        repo.add_message(session_id, "user", user_content)

        history = repo.get_messages(session_id, limit=_TRANSCRIPT_TURNS + 1)
        # Exclude the message we just added — it's passed separately
        # as `new_message`, not duplicated into the transcript.
        transcript = [(m.role, m.content) for m in history[:-1]][-_TRANSCRIPT_TURNS:]

        alert_context = _build_alert_context(repo.db, session.alert_trigger_id)

        base = (
            [session.symbol]
            if session.scope in ("symbol", "alert")
            and session.symbol
            and session.symbol != UNIVERSAL_SYMBOL
            else []
        )
        symbols, capped = resolve_turn_symbols(user_content, transcript, base)
        single = len(symbols) == 1

        def _ctx(sym: str) -> dict:
            return build_context(
                sym,
                include_news=single,
                include_fundamentals=single,
                include_divergence=single,
            ).to_dict()

        # The market baseline and each per-symbol context are independent
        # blocking calls (DB reads, a scan, aux-data HTTP) — fan them out.
        symbol_blocks: list[dict] = []
        unavailable: list[str] = []
        with ThreadPoolExecutor(max_workers=4) as ex:
            baseline_fut = ex.submit(build_market_baseline)
            ctx_futs = {sym: ex.submit(_ctx, sym) for sym in symbols}
            try:
                market_baseline = baseline_fut.result()
            except Exception as e:  # noqa: BLE001 — baseline never blocks the turn
                logger.warning("chat market baseline failed: %s", e)
                market_baseline = None
            for sym in symbols:  # preserve the resolved order
                try:
                    ctx = ctx_futs[sym].result()
                except InsufficientDataError:
                    unavailable.append(sym)
                    continue
                except Exception as e:  # noqa: BLE001 — per-symbol, never abort the turn
                    logger.warning("chat build_context(%s) failed: %s", sym, e)
                    unavailable.append(sym)
                    continue
                avail = _availability(ctx)
                symbol_blocks.append(
                    {"symbol": sym, "context": _prune_context(ctx, avail), "availability": avail}
                )

        reply_text, grounded = _generate_reply(
            symbol_blocks, unavailable, market_baseline, transcript,
            user_content, alert_context, capped, base,
        )
        grounded = grounded and not unavailable  # deterministic fail-safe

        focus = [b["symbol"] for b in symbol_blocks if b["availability"]["engine_warm"]]
        partial = [b["symbol"] for b in symbol_blocks if not b["availability"]["engine_warm"]]

        assistant_message = repo.add_message(session_id, "assistant", reply_text)
        return assistant_message, grounded, focus, partial, unavailable
    finally:
        repo.close()


def _availability(ctx: dict) -> dict:
    """Classify how much live quant data a context dict actually carries.

    ``engine_warm`` is the key signal: a ticker not in a watchlist gets
    a live price + best-effort indicators from ``build_context`` but its
    trend engine was never fed, so its multi-timeframe scores are all
    'unknown'/0.
    """
    tf_scores = ctx.get("timeframe_scores") or {}
    warm = bool(ctx.get("trend_state")) or any(
        (s or {}).get("direction") not in (None, "unknown", "neutral")
        and (s or {}).get("confidence", 0) > 0
        for s in tf_scores.values()
    )
    momentum = ctx.get("momentum") or {}
    return {
        "engine_warm": warm,
        "has_price": ctx.get("price") is not None,
        "has_rsi": momentum.get("rsi") is not None,
        "has_support_resistance": bool(ctx.get("support_resistance")),
        "note": "" if warm else (
            "not in your watchlist — live price / indicators only, "
            "no multi-timeframe trend or confidence"
        ),
    }


def _prune_context(ctx: dict, avail: dict) -> dict:
    """Drop empty sections, and — for a cold engine — the composite
    scores (market_structure / trend_transition) that read like a
    confidence number the model must not quote for an untracked name.
    """
    cold_only = {"market_structure", "trend_transition"}
    out: dict = {}
    for k, v in ctx.items():
        if v is None or v == {} or v == []:
            continue
        if not avail["engine_warm"] and k in cold_only:
            continue
        out[k] = v
    return out


def _generate_reply(
    symbol_blocks: list[dict],
    unavailable: list[str],
    market_baseline: dict | None,
    transcript: list[tuple[str, str]],
    user_content: str,
    alert_context: dict | None,
    capped: bool,
    base_symbols: list[str],
) -> tuple[str, bool]:
    """Call the AI and parse its reply. Never raises — degrades to a
    plain reply with grounded=False.

    When the AI's reply asks for ``wants_reanalysis``, runs the chat's
    one tool (see module docstring) for the named ticker instead.
    """
    # Friendly degrade for a legacy single-symbol session whose only
    # ticker has no data (keeps the pre-universal wording).
    if (
        not symbol_blocks
        and unavailable
        and base_symbols
        and set(unavailable) == {s.upper() for s in base_symbols}
    ):
        return f"I don't have enough data on {unavailable[0]} yet to answer that.", False

    if not ai_manager.is_available():
        return "AI is currently unavailable, so I can't answer that right now.", False

    capped_note = None
    if capped:
        shown = ", ".join(b["symbol"] for b in symbol_blocks) or "the first few"
        capped_note = (
            f"(You named more tickers than I can dig into at once — I looked at {shown}.)"
        )

    budget = max(2000, ai_manager.settings.max_tokens - 500)
    try:
        resp = ai_manager.complete(
            prompt=build_chat_prompt(
                symbol_blocks, unavailable, market_baseline, transcript,
                user_content, alert_context, capped_note=capped_note, token_budget=budget,
            ),
            system=CHAT_SYSTEM_PROMPT,
            max_tokens=500,
        )
    except Exception as e:  # noqa: BLE001
        logger.warning("Chat AI call raised: %s", e)
        return "Something went wrong reaching the AI provider — please try again.", False

    if resp.text is None:
        return "AI is currently unavailable, so I can't answer that right now.", False

    try:
        parsed = parse_chat_reply(resp.text)
    except Exception as e:  # noqa: BLE001
        logger.info("Chat reply failed to parse: %s", e)
        return "I couldn't process that — could you rephrase?", False

    if parsed.wants_reanalysis:
        known = [b["symbol"] for b in symbol_blocks]
        target = (parsed.reanalysis_symbol or "").upper().strip()
        if not target and len(known) == 1:
            target = known[0]
        if target and target in known:
            return _run_reanalysis(target)
        if known:
            return "Which ticker should I run the full analysis for?", True
        return "Tell me which ticker you'd like me to run the full analysis for.", False

    return parsed.reply, parsed.grounded


def _run_reanalysis(symbol: str) -> tuple[str, bool]:
    """Execute the chat's one tool call: a real analyze_symbol() run.

    Reuses analyze_symbol() itself — the same function
    AIAnalysisPanel's "Re-run" button calls — so a chat-triggered
    reanalysis carries the exact same safety contract (never raises;
    degrades to an UncertaintyResponse on AI-off/no-data/malformed
    reply). That degrade path is rendered here as a normal,
    grounded=False chat reply rather than surfaced as an error.
    """
    try:
        result = analyze_symbol(symbol)
    except Exception as e:  # noqa: BLE001 — the tool call must never crash the turn
        logger.warning("Chat-triggered reanalysis failed for %s: %s", symbol, e)
        return (
            "I tried to re-run the analysis but hit an error — please try again.",
            False,
        )

    if isinstance(result, UncertaintyResponse):
        return f"I tried to re-run the analysis for {symbol}, but {result.summary}", False

    return (
        f"I re-ran the analysis for {symbol}: trend is now {result.trend} "
        f"({result.confidence:.0%} confidence). {result.summary}",
        True,
    )
