"""
Version 4, AI feature 4 — conversational AI chat panel.

Scope (see docs/plan): single-turn-per-message (build_context() is
rebuilt fresh per message, not held as server-side "memory"), no
tool-calling, no streaming. Read-only relationship to features 1-3 —
this module never triggers a new analysis, digest, or alert
commentary; it only reads what already exists.

Follows analyze_symbol's "never raise for an expected failure mode"
contract: AI off, InsufficientDataError, or a malformed reply all
degrade to a stored assistant message explaining that (grounded=False)
rather than an HTTP error or a crashed request.
"""
from __future__ import annotations

import logging

from backend.ai.context import InsufficientDataError, build_context
from backend.ai.manager import ai_manager
from backend.ai.prompt import CHAT_SYSTEM_PROMPT, build_chat_prompt, parse_chat_reply
from backend.models import AlertTrigger, ChatMessage
from backend.repositories.chat_repository import ChatRepository

logger = logging.getLogger(__name__)

# How many prior turns (user + assistant messages combined) to include
# as transcript text in the prompt.
_TRANSCRIPT_TURNS = 6


def _build_alert_context(db, alert_trigger_id: int | None) -> dict | None:
    """Load the alert/trigger this chat was opened from, if any.

    Read-only — never re-triggers alert commentary generation, just
    reads what's already on the row (message/observed_value/
    ai_commentary if it's been generated by then).
    """
    if alert_trigger_id is None:
        return None
    trigger = db.query(AlertTrigger).filter(AlertTrigger.id == alert_trigger_id).first()
    if trigger is None:
        return None
    return {
        "symbol": trigger.symbol,
        "message": trigger.message,
        "observed_value": trigger.observed_value,
        "ai_commentary": trigger.ai_commentary,
        "triggered_at": str(trigger.triggered_at) if trigger.triggered_at else None,
    }


def answer_chat_message(session_id: int, user_content: str) -> tuple[ChatMessage, bool]:
    """Persist ``user_content`` as a user message, generate a reply,
    persist the assistant ChatMessage, and return ``(message,
    grounded)``.

    ``grounded`` isn't a persisted column (the stored transcript only
    has role/content, kept simple) — it's a per-turn hint for the
    immediate caller (the router's response), not part of chat
    history a later turn would need to see again.

    Never raises for an expected failure mode — AI-off, a
    context-building failure, or a malformed AI reply all produce a
    stored assistant message (grounded=False) explaining that, not an
    exception. An unexpected failure (e.g. the session doesn't exist)
    still raises — that's a caller bug, not a "the AI couldn't answer"
    case.
    """
    repo = ChatRepository()
    try:
        session = repo.get_session(session_id)
        if session is None:
            raise ValueError(f"chat session {session_id} not found")

        repo.add_message(session_id, "user", user_content)

        history = repo.get_messages(session_id, limit=_TRANSCRIPT_TURNS + 1)
        # Exclude the message we just added — it's passed separately
        # as `new_message`, not duplicated into the transcript.
        transcript = [(m.role, m.content) for m in history[:-1]][-_TRANSCRIPT_TURNS:]

        alert_context = _build_alert_context(repo.db, session.alert_trigger_id)

        reply_text: str
        grounded: bool
        try:
            context = build_context(session.symbol)
            context_dict = context.to_dict()
        except InsufficientDataError as e:
            logger.info("answer_chat_message: insufficient data for %s: %s", session.symbol, e)
            reply_text = (
                f"I don't have enough data on {session.symbol} yet to answer that."
            )
            grounded = False
        else:
            reply_text, grounded = _generate_reply(
                context_dict, transcript, user_content, alert_context,
            )

        assistant_message = repo.add_message(session_id, "assistant", reply_text)
        return assistant_message, grounded
    finally:
        repo.close()


def _generate_reply(
    context_dict: dict,
    transcript: list[tuple[str, str]],
    user_content: str,
    alert_context: dict | None,
) -> tuple[str, bool]:
    """Call the AI and parse its reply. Never raises — degrades to a
    plain "couldn't process" reply with grounded=False."""
    if not ai_manager.is_available():
        return "AI is currently unavailable, so I can't answer that right now.", False

    try:
        resp = ai_manager.complete(
            prompt=build_chat_prompt(context_dict, transcript, user_content, alert_context),
            system=CHAT_SYSTEM_PROMPT,
            max_tokens=300,
        )
    except Exception as e:  # noqa: BLE001
        logger.warning("Chat AI call raised: %s", e)
        return "Something went wrong reaching the AI provider — please try again.", False

    if resp.text is None:
        return "AI is currently unavailable, so I can't answer that right now.", False

    try:
        parsed = parse_chat_reply(resp.text)
    except Exception as e:  # noqa: BLE001
        logger.info("Chat reply failed to parse: %s", e)
        return "I couldn't process that — could you rephrase?", False

    return parsed.reply, parsed.grounded
