"""initial schema

Revision ID: 8175af1a213e
Revises: 
Create Date: 2026-08-28 16:58:37.929736+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8175af1a213e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('condition_type', sa.String(length=40), nullable=False),
    sa.Column('parameter', sa.String(length=120), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_is_enabled'), 'alerts', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_alerts_symbol'), 'alerts', ['symbol'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('signals_requested', sa.String(length=255), nullable=False),
    sa.Column('strategy_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_bars', sa.Integer(), nullable=True),
    sa.Column('total_signals', sa.Integer(), nullable=True),
    sa.Column('win_rate_1d', sa.Float(), nullable=True),
    sa.Column('avg_return_1d', sa.Float(), nullable=True),
    sa.Column('avg_return_5d', sa.Float(), nullable=True),
    sa.Column('avg_return_20d', sa.Float(), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('median_return_1d', sa.Float(), nullable=True),
    sa.Column('median_return_5d', sa.Float(), nullable=True),
    sa.Column('median_return_20d', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('mfe_avg', sa.Float(), nullable=True),
    sa.Column('mae_avg', sa.Float(), nullable=True),
    sa.Column('signal_frequency', sa.Float(), nullable=True),
    sa.Column('equity_curve_json', sa.Text(), nullable=True),
    sa.Column('out_of_sample', sa.Boolean(), nullable=True),
    sa.Column('overfitting_warning', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_created_at'), 'backtest_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_backtest_runs_id'), 'backtest_runs', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_runs_status'), 'backtest_runs', ['status'], unique=False)
    op.create_index(op.f('ix_backtest_runs_symbol'), 'backtest_runs', ['symbol'], unique=False)
    op.create_table('bars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('data_status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bars_id'), 'bars', ['id'], unique=False)
    op.create_index('ix_bars_provider_symbol', 'bars', ['provider', 'symbol'], unique=False)
    op.create_index(op.f('ix_bars_symbol'), 'bars', ['symbol'], unique=False)
    op.create_index('ix_bars_symbol_timeframe_timestamp', 'bars', ['symbol', 'timeframe', 'timestamp'], unique=True)
    op.create_index(op.f('ix_bars_timeframe'), 'bars', ['timeframe'], unique=False)
    op.create_index('ix_bars_timeframe_timestamp', 'bars', ['timeframe', 'timestamp'], unique=False)
    op.create_index(op.f('ix_bars_timestamp'), 'bars', ['timestamp'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('strategy_version', sa.String(length=50), nullable=False),
    sa.Column('parameters_json', sa.Text(), nullable=False),
    sa.Column('symbols', sa.String(length=500), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_start', sa.DateTime(), nullable=False),
    sa.Column('is_end', sa.DateTime(), nullable=False),
    sa.Column('val_start', sa.DateTime(), nullable=False),
    sa.Column('val_end', sa.DateTime(), nullable=False),
    sa.Column('oos_start', sa.DateTime(), nullable=True),
    sa.Column('oos_end', sa.DateTime(), nullable=True),
    sa.Column('signals_requested', sa.String(length=255), nullable=False),
    sa.Column('n_splits', sa.Integer(), nullable=False),
    sa.Column('val_pct', sa.Float(), nullable=False),
    sa.Column('oos_pct', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_win_rate', sa.Float(), nullable=True),
    sa.Column('is_avg_return_1d', sa.Float(), nullable=True),
    sa.Column('is_avg_return_5d', sa.Float(), nullable=True),
    sa.Column('is_avg_return_20d', sa.Float(), nullable=True),
    sa.Column('is_median_return_1d', sa.Float(), nullable=True),
    sa.Column('is_sharpe', sa.Float(), nullable=True),
    sa.Column('is_profit_factor', sa.Float(), nullable=True),
    sa.Column('is_max_drawdown', sa.Float(), nullable=True),
    sa.Column('is_total_signals', sa.Integer(), nullable=True),
    sa.Column('is_signal_frequency', sa.Float(), nullable=True),
    sa.Column('val_win_rate', sa.Float(), nullable=True),
    sa.Column('val_avg_return_1d', sa.Float(), nullable=True),
    sa.Column('val_avg_return_5d', sa.Float(), nullable=True),
    sa.Column('val_avg_return_20d', sa.Float(), nullable=True),
    sa.Column('val_median_return_1d', sa.Float(), nullable=True),
    sa.Column('val_sharpe', sa.Float(), nullable=True),
    sa.Column('val_profit_factor', sa.Float(), nullable=True),
    sa.Column('val_max_drawdown', sa.Float(), nullable=True),
    sa.Column('val_total_signals', sa.Integer(), nullable=True),
    sa.Column('val_signal_frequency', sa.Float(), nullable=True),
    sa.Column('oos_win_rate', sa.Float(), nullable=True),
    sa.Column('oos_avg_return_1d', sa.Float(), nullable=True),
    sa.Column('oos_avg_return_5d', sa.Float(), nullable=True),
    sa.Column('oos_avg_return_20d', sa.Float(), nullable=True),
    sa.Column('oos_median_return_1d', sa.Float(), nullable=True),
    sa.Column('oos_sharpe', sa.Float(), nullable=True),
    sa.Column('oos_profit_factor', sa.Float(), nullable=True),
    sa.Column('oos_max_drawdown', sa.Float(), nullable=True),
    sa.Column('oos_total_signals', sa.Integer(), nullable=True),
    sa.Column('oos_signal_frequency', sa.Float(), nullable=True),
    sa.Column('overfit_score', sa.Float(), nullable=True),
    sa.Column('overfitting_warning', sa.String(length=500), nullable=True),
    sa.Column('run_ids_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'strategy_version')
    )
    op.create_index(op.f('ix_experiments_created_at'), 'experiments', ['created_at'], unique=False)
    op.create_index(op.f('ix_experiments_id'), 'experiments', ['id'], unique=False)
    op.create_index(op.f('ix_experiments_name'), 'experiments', ['name'], unique=False)
    op.create_index(op.f('ix_experiments_status'), 'experiments', ['status'], unique=False)
    op.create_index(op.f('ix_experiments_strategy_version'), 'experiments', ['strategy_version'], unique=False)
    op.create_table('historical_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('trend_state', sa.String(length=20), nullable=True),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('market_regime', sa.String(length=20), nullable=True),
    sa.Column('relative_strength', sa.String(length=30), nullable=True),
    sa.Column('sector_alignment', sa.Float(), nullable=True),
    sa.Column('volume_state', sa.String(length=20), nullable=True),
    sa.Column('momentum', sa.Float(), nullable=True),
    sa.Column('structure', sa.String(length=20), nullable=True),
    sa.Column('confidence_inputs', sa.Text(), nullable=True),
    sa.Column('strategy_version', sa.String(length=20), nullable=True),
    sa.Column('data_quality', sa.String(length=20), nullable=True),
    sa.Column('return_5b', sa.Float(), nullable=True),
    sa.Column('return_10b', sa.Float(), nullable=True),
    sa.Column('return_20b', sa.Float(), nullable=True),
    sa.Column('mfe', sa.Float(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('outcome_computed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_signals_id'), 'historical_signals', ['id'], unique=False)
    op.create_index(op.f('ix_historical_signals_outcome_computed'), 'historical_signals', ['outcome_computed'], unique=False)
    op.create_index(op.f('ix_historical_signals_symbol'), 'historical_signals', ['symbol'], unique=False)
    op.create_index(op.f('ix_historical_signals_timeframe'), 'historical_signals', ['timeframe'], unique=False)
    op.create_index(op.f('ix_historical_signals_timestamp'), 'historical_signals', ['timestamp'], unique=False)
    op.create_table('market_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('next_open', sa.DateTime(), nullable=True),
    sa.Column('next_close', sa.DateTime(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_status_id'), 'market_status', ['id'], unique=False)
    op.create_index(op.f('ix_market_status_symbol'), 'market_status', ['symbol'], unique=False)
    op.create_index('ix_market_status_symbol_timestamp', 'market_status', ['symbol', 'timestamp'], unique=False)
    op.create_index(op.f('ix_market_status_timestamp'), 'market_status', ['timestamp'], unique=False)
    op.create_table('provider_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('is_healthy', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('rate_limit_remaining', sa.Integer(), nullable=True),
    sa.Column('last_success', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_status_id'), 'provider_status', ['id'], unique=False)
    op.create_index(op.f('ix_provider_status_provider_name'), 'provider_status', ['provider_name'], unique=False)
    op.create_index('ix_provider_status_provider_timestamp', 'provider_status', ['provider_name', 'timestamp'], unique=False)
    op.create_index(op.f('ix_provider_status_timestamp'), 'provider_status', ['timestamp'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('data_status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_id'), 'quotes', ['id'], unique=False)
    op.create_index('ix_quotes_provider_symbol', 'quotes', ['provider', 'symbol'], unique=False)
    op.create_index(op.f('ix_quotes_symbol'), 'quotes', ['symbol'], unique=False)
    op.create_index('ix_quotes_symbol_timestamp', 'quotes', ['symbol', 'timestamp'], unique=False)
    op.create_index(op.f('ix_quotes_timestamp'), 'quotes', ['timestamp'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_id'), 'watchlists', ['id'], unique=False)
    op.create_table('alert_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('observed_value', sa.String(length=120), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_triggers_alert_id'), 'alert_triggers', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_triggers_id'), 'alert_triggers', ['id'], unique=False)
    op.create_index(op.f('ix_alert_triggers_symbol'), 'alert_triggers', ['symbol'], unique=False)
    op.create_index(op.f('ix_alert_triggers_triggered_at'), 'alert_triggers', ['triggered_at'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('signal', sa.String(length=40), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_date_1d', sa.DateTime(), nullable=True),
    sa.Column('exit_price_1d', sa.Float(), nullable=True),
    sa.Column('return_1d', sa.Float(), nullable=True),
    sa.Column('exit_date_5d', sa.DateTime(), nullable=True),
    sa.Column('exit_price_5d', sa.Float(), nullable=True),
    sa.Column('return_5d', sa.Float(), nullable=True),
    sa.Column('exit_date_20d', sa.DateTime(), nullable=True),
    sa.Column('exit_price_20d', sa.Float(), nullable=True),
    sa.Column('return_20d', sa.Float(), nullable=True),
    sa.Column('mfe', sa.Float(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('regime_at_entry', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_trades_id'), 'backtest_trades', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_trades_run_id'), 'backtest_trades', ['run_id'], unique=False)
    op.create_table('watchlist_symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_symbols_id'), 'watchlist_symbols', ['id'], unique=False)
    op.create_index(op.f('ix_watchlist_symbols_symbol'), 'watchlist_symbols', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_symbols_symbol'), table_name='watchlist_symbols')
    op.drop_index(op.f('ix_watchlist_symbols_id'), table_name='watchlist_symbols')
    op.drop_table('watchlist_symbols')
    op.drop_index(op.f('ix_backtest_trades_run_id'), table_name='backtest_trades')
    op.drop_index(op.f('ix_backtest_trades_id'), table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index(op.f('ix_alert_triggers_triggered_at'), table_name='alert_triggers')
    op.drop_index(op.f('ix_alert_triggers_symbol'), table_name='alert_triggers')
    op.drop_index(op.f('ix_alert_triggers_id'), table_name='alert_triggers')
    op.drop_index(op.f('ix_alert_triggers_alert_id'), table_name='alert_triggers')
    op.drop_table('alert_triggers')
    op.drop_index(op.f('ix_watchlists_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_quotes_timestamp'), table_name='quotes')
    op.drop_index('ix_quotes_symbol_timestamp', table_name='quotes')
    op.drop_index(op.f('ix_quotes_symbol'), table_name='quotes')
    op.drop_index('ix_quotes_provider_symbol', table_name='quotes')
    op.drop_index(op.f('ix_quotes_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_provider_status_timestamp'), table_name='provider_status')
    op.drop_index('ix_provider_status_provider_timestamp', table_name='provider_status')
    op.drop_index(op.f('ix_provider_status_provider_name'), table_name='provider_status')
    op.drop_index(op.f('ix_provider_status_id'), table_name='provider_status')
    op.drop_table('provider_status')
    op.drop_index(op.f('ix_market_status_timestamp'), table_name='market_status')
    op.drop_index('ix_market_status_symbol_timestamp', table_name='market_status')
    op.drop_index(op.f('ix_market_status_symbol'), table_name='market_status')
    op.drop_index(op.f('ix_market_status_id'), table_name='market_status')
    op.drop_table('market_status')
    op.drop_index(op.f('ix_historical_signals_timestamp'), table_name='historical_signals')
    op.drop_index(op.f('ix_historical_signals_timeframe'), table_name='historical_signals')
    op.drop_index(op.f('ix_historical_signals_symbol'), table_name='historical_signals')
    op.drop_index(op.f('ix_historical_signals_outcome_computed'), table_name='historical_signals')
    op.drop_index(op.f('ix_historical_signals_id'), table_name='historical_signals')
    op.drop_table('historical_signals')
    op.drop_index(op.f('ix_experiments_strategy_version'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_status'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_name'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_created_at'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_bars_timestamp'), table_name='bars')
    op.drop_index('ix_bars_timeframe_timestamp', table_name='bars')
    op.drop_index(op.f('ix_bars_timeframe'), table_name='bars')
    op.drop_index('ix_bars_symbol_timeframe_timestamp', table_name='bars')
    op.drop_index(op.f('ix_bars_symbol'), table_name='bars')
    op.drop_index('ix_bars_provider_symbol', table_name='bars')
    op.drop_index(op.f('ix_bars_id'), table_name='bars')
    op.drop_table('bars')
    op.drop_index(op.f('ix_backtest_runs_symbol'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_status'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_id'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_created_at'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_index(op.f('ix_alerts_symbol'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_enabled'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
